/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.sun.source.tree.BreakTree;
import datatest.alter_person;
import datatest.connect_person;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author joker
 */
public class alter_table extends javax.swing.JFrame {

    /**
     * Creates new form alter_table
     */
    public alter_table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        new_name = new javax.swing.JLabel();
        Nname_field = new javax.swing.JTextField();
        updateB = new javax.swing.JButton();
        confirmed = new javax.swing.JLabel();
        confirmed_field = new javax.swing.JTextField();
        new_age = new javax.swing.JLabel();
        new_height = new javax.swing.JLabel();
        Nage_field = new javax.swing.JTextField();
        Nheight_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        new_name.setText("novo nome");

        updateB.setText("ATUALIZAR");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        confirmed.setText("cpf para confirmação");

        new_age.setText("redefinir idade");

        new_height.setText("redefinir altura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(new_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(new_age)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Nname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmed)
                                    .addComponent(Nage_field, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(confirmed_field, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(new_height))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Nheight_field, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(updateB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(new_name))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(new_age)
                            .addComponent(new_height))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nage_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nheight_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(confirmed)
                .addGap(18, 18, 18)
                .addComponent(confirmed_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(updateB)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        
        String rename = Nname_field.getText();
        String cpf = confirmed_field.getText();  
        int reage;
        float reheight;
        alter_person altering = new alter_person();
        
        rename = rename.toLowerCase();
        
        
        if ("".equals(cpf)) 
        {
            JOptionPane.showMessageDialog(null,"CPF NULO OU INVÁLIDO: alteração de dados não foi efetuada e a janela será fechada, favor inserir cpf na próxima vez");
        }
        else
        {
            altering.verify_cpf(cpf);            
        }
        
        if ("".equals(Nage_field.getText())) 
        {
            reage = 0;
        }
        else
        {
            reage = Integer.parseInt(Nage_field.getText());
        }
        
        if ("".equals(Nheight_field.getText())) 
        {
            reheight = 0;
        }
        else
        {
            reheight = Float.parseFloat(Nheight_field.getText());
        }
        
        
        if (reage <= 0 && reheight <= 0)
        {
            altering.alter(cpf, rename);
        }
        else if ("".equals(rename) && reheight <= 0) 
        {
            altering.alter(cpf, reage);
        }
        else if ("".equals(rename) && reage <= 0) 
        {
            altering.alter(cpf, reheight);
        }
        else if ("".equals(rename)) 
        {
            altering.alter(cpf, reage,reheight);
        }
        else if (reheight <= 0) 
        {
            altering.alter(cpf,rename,reage);
        }
        else if (reage <= 0) 
        {
            altering.alter(cpf,rename,reheight);
        }
        else
        {
            altering.alter(cpf, rename, reage, reheight);
        }
        
        
        setVisible(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        
    }//GEN-LAST:event_updateBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alter_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alter_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alter_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alter_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alter_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nage_field;
    private javax.swing.JTextField Nheight_field;
    private javax.swing.JTextField Nname_field;
    private javax.swing.JLabel confirmed;
    private javax.swing.JTextField confirmed_field;
    private javax.swing.JLabel new_age;
    private javax.swing.JLabel new_height;
    private javax.swing.JLabel new_name;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
